export default {
    ACTIVE_ORGANIZATION_SET: 'ACTIVE_ORGANIZATION_SET',
    AUTH_USER_SET: 'AUTH_USER_SET',
    INVOICES_FROM_SET: 'INVOICES_FROM_SET',
    INVOICES_TO_SET: 'INVOICES_TO_SET',
    INVOICES_PARAM_SET: 'INVOICES_PARAM_SET',
    EDIT_INVOICE_SET: 'EDIT_INVOICE_SET',
    LOGIN_LOGOUT_PAGE_SET: 'LOGIN_LOGOUT_PAGE_SET',
    MASKDIV_SET: 'MASKDIV_SET',
    ORGANIZATION_CLIENTS_SEARCH_SET: 'ORGANIZATION_CLIENTS_SEARCH_SET',
    ORGANIZATION_CLIENTS_SET: 'ORGANIZATION_CLIENTS_SET',
    ORGANIZATIONS_SET: 'ORGANIZATIONS_SET',
    USERDATA_SET: 'USERDATA_SET',
};
